# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'APIUnitTesting' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for APIUnitTesting

  target 'APIUnitTestingTests' do
    inherit! :search_paths

    # Pods for testing
  end

  target 'APIUnitTestingUITests' do
    # Pods for testing
  end

end
